color0 #1f231a
color1 #fd4663
color2 #b2e467
color3 #66d65c
color4 #66ccc0
color5 #c8ec93
color6 #9de996
color7 #f2f3f2
color8 #666e5a
color9 #fd4663
color10 #b2e467
color11 #66d65c
color12 #66ccc0
color13 #c8ec93
color14 #9de996
color15 #f2f3f2

cursor                #f2f3f2
cursor_text_color     #1f231a
background            #1f231a
foreground            #f2f3f2
selection_foreground  #b3b6af
selection_background  #2a2f23
active_border_color   #b2e467
inactive_border_color #2a2f23
url_color             #b2e467

active_tab_foreground   #202518
active_tab_background   #b2e467
inactive_tab_foreground #b3b6af
inactive_tab_background #2a2f23
cursor_trail_color      #b3b6af
