# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=desc:BOE 0x0C8B 0x00000068,highrr,0x0,1
monitor=eDP-1,highrr,0x0,1
monitor=desc:Microstep MPG321UX OLED 0x01010101,highrr@,auto-center-up,1
